export const WORD_PAIRS = [
  { civilian: "Door", undercover: "Handle" },
  { civilian: "Bed", undercover: "Pillow" },
  { civilian: "Knife", undercover: "Fork" },
  { civilian: "Bottle", undercover: "Water" },
  { civilian: "Key", undercover: "Ring" },
  { civilian: "Fan", undercover: "Air" },
  { civilian: "Sun", undercover: "Sky" },
  { civilian: "Tree", undercover: "Leaf" },
  { civilian: "Beach", undercover: "Sand" },
  { civilian: "Cloud", undercover: "Rain" },
  { civilian: "Tea", undercover: "Coffee" },
  { civilian: "Salt", undercover: "Pepper" },
  { civilian: "Doctor", undercover: "Patient" },
  { civilian: "Mother", undercover: "Child" },
  { civilian: "Date", undercover: "Calendar" },
  { civilian: "Map", undercover: "Direction" },
  { civilian: "Needle", undercover: "Thread" },
  { civilian: "Switch", undercover: "Light" },
  { civilian: "Curtain", undercover: "Window" },
  { civilian: "Stove", undercover: "Flame" },
  { civilian: "Pillow", undercover: "Cover" },
  { civilian: "Blanket", undercover: "Warmth" },
  { civilian: "Shelf", undercover: "Book" },
  { civilian: "Carpet", undercover: "Floor" },
  { civilian: "Clock", undercover: "Wall" },
  { civilian: "Brush", undercover: "Paint" }
];
